modLoader="javafml"
loaderVersion="[2,)"
license="Apache License version 2.0"

[[mods]]
modId="new_nether_stuff"
version="0.1.0"
displayName="New Nether Stuff"
displayURL="https://github.com/Kaisoneo"
logoFile="logo.png"
credits="Thanks to me. "
authors="Kaisoneo"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.new_nether_stuff]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.117,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.new_nether_stuff]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6]"
    ordering="AFTER"
    side="BOTH"




[[mixins]]
    config="mixins.new_nether_stuff.json"

# Start of user code block dependencies configuration
# End of user code block dependencies configuration